{ config, pkgs, ... }:
{
  imports = [
    # Autogenerated by nixos installer
    ./hardware-configuration.nix
    # Import common system configuration
    ./system/system.nix
    # Override common config with machine specific config
    ./machines/detect.nix
    # Home manager config
    ./home/bootstrap.nix
  ];
}
