{ config, pkgs, ... }:
{
  imports = [
    # Autogenerated by nixos installer
    ./hardware-configuration.nix
    # Import common system configuration
    ./system
    # Override common config with machine specific config
    ./machines
    # Home manager config
    ./home
  ];
}
