set nocompatible
filetype plugin indent on

" Color scheme
syntax on
set background=dark
colorscheme solarized
hi Normal ctermbg=none

" Tab Sizes
set tabstop=2
set softtabstop=2
set shiftwidth=2

set cc=80

set hidden

set hlsearch
set encoding=utf-8

set expandtab

" Automatic Indenting
set smarttab
set autoindent

" Persit undos between files and restarts
set undofile
set undodir=$HOME/.vim/undo-dir

" Turn on line numbers
set number

let g:airline_solarized_bg='dark'
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'

autocmd BufNewFile,BufRead *.s :set filetype=gas

" Keybinds
map <Tab> <C-^>
